CREATE TABLE IF NOT EXISTS subscription_credits (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  estabelecimento_id INT NOT NULL,
  source_subscription_id INT NOT NULL,
  target_subscription_id INT NULL,
  source_plan ENUM('starter','pro','premium') NOT NULL,
  target_plan ENUM('starter','pro','premium') NOT NULL,
  source_cycle_started_at DATETIME NULL,
  source_cycle_ends_at DATETIME NULL,
  changed_at DATETIME NOT NULL,
  original_plan_amount_cents INT NOT NULL,
  generated_credit_cents INT NOT NULL,
  reserved_credit_cents INT NOT NULL DEFAULT 0,
  consumed_credit_cents INT NOT NULL DEFAULT 0,
  remaining_credit_cents INT NOT NULL DEFAULT 0,
  payment_method ENUM('credit_card','pix') NULL,
  source_payment_id VARCHAR(120) NULL,
  source_external_reference VARCHAR(191) NULL,
  reason VARCHAR(40) NOT NULL DEFAULT 'upgrade_proration',
  unique_key VARCHAR(191) NOT NULL,
  status ENUM('available','partially_reserved','reserved','partially_consumed','consumed','released','voided') NOT NULL DEFAULT 'available',
  audit_payload LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_subscription_credits_unique_key (unique_key),
  INDEX idx_subscription_credits_estab_status (estabelecimento_id, status),
  INDEX idx_subscription_credits_target_sub (target_subscription_id),
  INDEX idx_subscription_credits_source_sub (source_subscription_id),
  CONSTRAINT fk_subscription_credits_estab FOREIGN KEY (estabelecimento_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscription_credits_source_sub FOREIGN KEY (source_subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscription_credits_target_sub FOREIGN KEY (target_subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS subscription_credit_applications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  credit_id BIGINT NOT NULL,
  estabelecimento_id INT NOT NULL,
  target_subscription_id INT NOT NULL,
  payment_method ENUM('credit_card','pix') NULL,
  application_type VARCHAR(40) NOT NULL,
  application_group_key VARCHAR(191) NOT NULL,
  application_key VARCHAR(191) NOT NULL,
  scheduled_for DATETIME NULL,
  payment_id VARCHAR(120) NULL,
  external_reference VARCHAR(191) NULL,
  amount_cents INT NOT NULL,
  status ENUM('scheduled','applied','released') NOT NULL DEFAULT 'scheduled',
  payload LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_subscription_credit_app_key (application_key),
  INDEX idx_subscription_credit_app_sub_status (target_subscription_id, status, scheduled_for),
  INDEX idx_subscription_credit_app_credit (credit_id),
  CONSTRAINT fk_subscription_credit_app_credit FOREIGN KEY (credit_id) REFERENCES subscription_credits(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscription_credit_app_estab FOREIGN KEY (estabelecimento_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscription_credit_app_sub FOREIGN KEY (target_subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
